version: '3.8'

services:
  gpu-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gpu-dashboard
    ports:
      - "3000:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - dashboard-network

  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: unless-stopped
    env_file:
      - .env
    command: tunnel --no-autoupdate run
    depends_on:
      gpu-dashboard:
        condition: service_healthy
    networks:
      - dashboard-network
    environment:
      - TUNNEL_METRICS=0.0.0.0:2000
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:2000/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  dashboard-network:
    driver: bridge