version: '3.8'

services:
  gpu-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gpu-dashboard
    ports:
      - "3000:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - dashboard-network

networks:
  dashboard-network:
    driver: bridge